### ISSUE TITLE
centreon daemonset-status not reporting pods correctly

### ISSUE THREAD

**Issue by Martin-Barr** [centreon/centreon-plugins#3667]
Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English

## Bug/Question

I am using the centreon plugin for Kubernentes to monitor using icinga2 AWS EKS services. I have successfully implemented all basic checks pods, deployments statefulset-status and these are working and reporting okay.

The code I am using is as follows for daemonset-status: As it is AWS I have exported the location of the config file first.

```bash
 perl /opt/data01/monitoring/centreon-plugins/centreon_plugins.pl --config-file '/opt/primary-ic2-01/kube/EKSMAMUAT1.config' --context 'EKSMAMUAT1' --custommode 'kubectl' --mode 'daemonset-status' --plugin 'cloud::kubernetes::plugin'
OK: All DaemonSets status are ok | 'aws-node#daemonset.pods.desired.count'=0;;;; 'aws-node#daemonset.pods.current.count'=0;;;; 'aws-node#daemonset.pods.available.count'=0;;;; 'aws-node#daemonset.pods.uptodate.count'=0;;;; 'aws-node#daemonset.pods.ready.count'=0;;;; 'aws-node#daemonset.pods.misscheduled.count'=0;;;; 'filebeat#daemonset.pods.desired.count'=0;;;; 'filebeat#daemonset.pods.current.count'=0;;;; 'filebeat#daemonset.pods.available.count'=0;;;; 'filebeat#daemonset.pods.uptodate.count'=0;;;; 'filebeat#daemonset.pods.ready.count'=0;;;; 'filebeat#daemonset.pods.misscheduled.count'=0;;;; 'node-exporter#daemonset.pods.desired.count'=0;;;; 'node-exporter#daemonset.pods.current.count'=0;;;; 'node-exporter#daemonset.pods.available.count'=0;;;; 'node-exporter#daemonset.pods.uptodate.count'=0;;;; 'node-exporter#daemonset.pods.ready.count'=0;;;; 'node-exporter#daemonset.pods.misscheduled.count'=0;;;; 'kube-proxy#daemonset.pods.desired.count'=0;;;; 'kube-proxy#daemonset.pods.current.count'=0;;;; 'kube-proxy#daemonset.pods.available.count'=0;;;; 'kube-proxy#daemonset.pods.uptodate.count'=0;;;; 'kube-proxy#daemonset.pods.ready.count'=0;;;; 'kube-proxy#daemonset.pods.misscheduled.count'=0;;;;
```

From this output I only see 0 being returned. when I am expecting 4
I am using kubectl
I have tested the same check with kubectl and get the following.

```bash
 kubectl --kubeconfig /opt/primary-ic2-01/kube/EKSMAMUAT1.config get daemonsets --all-namespaces
NAMESPACE      NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system    aws-node        4         4         4       4            4           <none>          216d
kube-system    kube-proxy      4         4         4       4            4           <none>          216d
lens-metrics   node-exporter   4         4         4       4            4           <none>          215d
xxxxxxxx-uat   filebeat        4         4         0       4            0           <none>          106d

kubectl --kubeconfig /opt/primary-ic2-01/kube/EKSMAMUAT1.config get daemonsets --all-namespaces
NAMESPACE      NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system    aws-node        4         4         4       4            4           <none>          216d
kube-system    kube-proxy      4         4         4       4            4           <none>          216d
lens-metrics   node-exporter   4         4         4       4            4           <none>          215d
xxxxxxxx-uat   filebeat        4         4         3       4            3           <none>          106d

 kubectl --kubeconfig /opt/primary-ic2-01/kube/EKSMAMUAT1.config get daemonsets --all-namespaces
NAMESPACE      NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system    aws-node        4         4         4       4            4           <none>          216d
kube-system    kube-proxy      4         4         4       4            4           <none>          216d
lens-metrics   node-exporter   4         4         4       4            4           <none>          215d
meridian-uat   filebeat        4         4         4       4            4           <none>          106d
```

This happened to be a the start-up of the cluster this morning. As you can see the filebeat was 0 then 3 then 4, the perl code still shows 0

I have also run the perl command with the --debug (removed actual http address)

```bash
 perl /opt/data01/monitoring/centreon-plugins/centreon_plugins.pl --config-file '/opt/primary-ic2-01/kube/EKSMAMUAT1.config' --context 'EKSMAMUAT1' --custommode 'kubectl' --mode 'daemonset-status' --plugin 'cloud::kubernetes::plugin' --debug
```
I have removed the truncated code to make this more readable.

```bash
Command line: 'kubectl get daemonsets --all-namespaces --output='json' --kubeconfig='/opt/primary-ic2-01/kube/EKSMAMUAT1.config' --request-timeout='10' --context='EKSMAMUAT1' --v='9''
DaemonSet 'aws-node' Pods Desired: 0, Current: 0, Available: 0, Up-to-date: 0, Ready: 0, Misscheduled: 0
DaemonSet 'filebeat' Pods Desired: 0, Current: 0, Available: 0, Up-to-date: 0, Ready: 0, Misscheduled: 0
DaemonSet 'node-exporter' Pods Desired: 0, Current: 0, Available: 0, Up-to-date: 0, Ready: 0, Misscheduled: 0
DaemonSet 'kube-proxy' Pods Desired: 0, Current: 0, Available: 0, Up-to-date: 0, Ready: 0, Misscheduled: 0
```

Have there been any other reports of this?
Is this something that can be investigated?
Am I missing something in this check?

**Comment by garnier-quentin** [comment]
The json response is truncated. Could you execute the command line directly and provide the full json ?
```kubectl get daemonsets --all-namespaces --output='json' --kubeconfig='/opt/primary-ic2-01/kube/EKSMAMUAT1.config' --request-timeout='10' --context='EKSMAMUAT1' --v='9'```

**Comment by Martin-Barr** [comment]
Hi Quentin, thank you for you response. I attached a txt file with the json output.

[json_daemonset.txt](https://github.com/centreon/centreon-plugins/files/8717218/json_daemonset.txt)

**Comment by Martin-Barr** [comment]
Hi Quentin, I did some checking of output formats for the centreon plugin and got the results in a JSON format.

The txt file attached contains the command run and the output file which I converted to JSON
[centreon_daemonset.txt](https://github.com/centreon/centreon-plugins/files/8717871/centreon_daemonset.txt)

**Comment by garnier-quentin** [comment]
It's fixed in last version. You can test it

**Comment by Martin-Barr** [comment]
Hi Quentin, what is the latest Version?

**Comment by garnier-quentin** [comment]
Le voici: https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip

**Comment by Martin-Barr** [comment]
Hi Quentin, I am still getting the same result.
I have the reposiroty as a submodule in my Icinga2 environment and have done the following:

```bash
git submodule update --init
```

This pulled down all the updates. This included the daemonset_status.pm update, as far as I can see the code has only change the date.

I have run the command link check and get exactly the same result, so it is not fixed.

**Comment by garnier-quentin** [comment]
i don't know how you manage it with icinga. But thanks for the feedback, that it's fixed
